t3n:
  SEO:
    Routing:
      redirect:
        enable:
          trailingSlash: true
          toLowerCase: false
        statusCode: 301
      blacklist:
        '/neos/.*': true

Neos:
  Flow:
    http:
      middlewares:
        'routing':
          middleware: 't3n\SEO\Routing\RoutingMiddleware'
