Yeebase:
  SEO:
    Routing:
      redirect:
        enable: TRUE
        statusCode: 303
      blacklist:
        '/neos/.*': TRUE

Neos:
  Flow:
    http:
      chain:
        process:
          chain:
            routing:
              component: 'Yeebase\SEO\Routing\RoutingComponent'
